### ISSUE TITLE
desktop as webcam

### ISSUE THREAD

**Issue by jrsmile** [geerlingguy/uvc-gadget#6]
Hi, i am working on an idea and could not think of another way to contact you.
currently i am trying to forward the pi's desktop as a uvc-gadget to a host pc.
and use a serial connection as way back to the pi.

the concept would have a usb composite interface.
uvc-gadget
serial-hid
massstorage-cdrom

the usage would be to use the pi zero-w in combination with a usb-a adapter board as host powered compute stick.
it boots and shows up as cd-rom drive.
on the cd image there will be a little software that shows the pi-desktop via uvc-gadget livestream
and graps the relative keyboard and mouse inputs and forards them via serial to the pi.

the end result would be a secure surf stick with bluetooth and wlan function that has no ethernet connection to the host but can be fully worked with remotely.

 it might even be possible to switch from cd-rom to hdd image and present securely downloaded files to the hostfilesystem.

please let me know if you want to join this project.

Best regards,
JR.

**Comment by geerlingguy** [comment]
@jrsmile - Sounds like a fun possibility, but I won't be able to help with the project personally.
